---
Name: gridfieldqueuedexport
Only:
  ModuleExists: 'userforms'
After:
  - 'userforms/*'
---
SilverStripe\UserForms\Model\UserDefinedForm:
  extensions:
    - SilverStripe\GridfieldQueuedExport\Extensions\UserFormUseQueuedExportExtension
